### PR TITLE
Drop animations on headers

### PR DESCRIPTION
**Pull request by ddevault**

### CODE REVIEW

**Comment by eatonphil** [comment]
Looks good. Can we merge the three svgs into one jpg now?

**Comment by ddevault** [comment]
Why? The SVG is probably lighter weight anyway and uses vector graphics instead of raster graphics.

**Comment by eatonphil** [comment]
Not a big deal. I normally think of jpegs for images, svg for icons/logos. Having it in one makes it a little more clear they belong together outside of the html.

**Comment by eatonphil** [comment]
Whoops. Read it as "merge and comment".

**Comment by ddevault** [comment]
ty

**Pull request merged**
